#!/bin/bash
echo ------------
:(){
    echo "i'm a function, my name is "$FUNCNAME
}
:
echo ------------
var1=$1
(( var0 = var1 < 10 ? 0:1 ))
echo $var0
echo ------------
a="a outside"
echo $a
( a="a inside"; echo $a )
echo $a
echo ------------
echo {a,b}' '{c,d}
echo {file1,file2}\ :{\ A," B",' C'}
echo ------------
echo {a..c}{3..10}
base64_charset=( {A..Z} {a..z} {0..9} + / = )
echo 'base64:' ${base64_charset[@]}
echo ------------
exit 1
a=2;b=4
echo $(( a+b ))
echo $(( b%a ))
echo ------------
ls /home/liubida &
echo Done.
wait
echo ------------
hello=" a  b c"
echo $hello
echo "$hello"
ls=`ls -al`
echo $ls
echo "$ls"
echo ------------



